name: Bug
description: Open a new issue to describe a bug. 
title: "[Bug]: "
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: >
      Please describe the details of any bug you have found. Developers need to know specific details of what you found, where, and how this different from what you expect. _Need help filling this out? Once you have your feature details in hand, contact us and we'll help step you through filling out this issue._
- type: markdown
  attributes:
    value: |
      # Describe the bug
      _Please provide a summary about the bug in the following form._
- type: textarea
  id: repro
  attributes:
    label: Steps to reproduce the bug
    description: "How do you trigger this bug? Please walk us through it step by step. Try something like, When I do x, then I do y, and do z, I see this error"
    value: |
      1.
      2.
      3. 
      ...
    render: bash
  validations:
    required: true
- type: textarea
  id: bug_screenshot
  attributes:
    label: Screenshot
    description: Drag/drop your image/s here
  validations:
    required: false
- type: textarea
  id: expected_behavior
  attributes:
    label: Expected behavior
    description: Describe briefly what you expect to happen.
    placeholder: When I do a, I expect b, c, d
  validations:
    required: false
- type: textarea
  id: extra_screenshots
  attributes:
    label: Additional Screenshots
    description: If applicable, add screenshots to help explain your problem. Drag/drop your image/s here
  validations:
    required: false
- type: input
  id: taxonpages_site
  attributes:
    label: TaxonPages Site URL
    description: Which website has this bug, please put the URL here, use "local for development environments
    placeholder: https://orthoptera.speciesfile.org/, local
- type: input
  id: taxonpages_panel
  attributes:
    label: TaxonPages Panel
    description: (optional) Provide which TaxonPages Panel has this bug
    placeholder: Nomenclature, Map, Literature
- type: input
  id: browser_used
  attributes:
    label: Browser Used
    description: Please share the browser and its version you were using.
    placeholder: (e.g. chrome, firefox)
