---
  project_name: World Auchenorrhyncha Database
  project_citation: World Auchenorrhyncha Database
  project_url: https://proceps.github.io/auchenorrhyncha/#/
  project_authors: Dmitriev, Dmitry A.; Blanco-Rodriguez, E.; Borodin, Oleg I.; Cao, Yang-Hui; Dietrich, Christopher H.; Dmitrieva, Margarita O.; McKamey, Stuart; Novoselova, Marina; Pinedo-Escatel, Jorge Adilson; Rakitov, Roman A., Sanborn, Allen F., Takiya, Daniela M., Zahniser, James N.
