---
  project_name: "World Auchenorrhyncha Database"
  project_citation: "TaxonPages: World Auchenorrhyncha Database"
  project_url: https://hoppers.speciesfile.org/
  project_authors: "Dmitriev, Dmitry A.; Blanco-Rodríguez, Edith; Borodin, Oleg I.; Cao, Yang-Hui; Deitz, Lewis L.; Dietrich, Christopher H.; Dmitrieva, Margarita O.; El-Sonbati, Saad A.; Evangelista, Olivia; McKamey, Stuart; Morris, Brendan O.; Novoselova, Marina; Pinedo-Escatel, Jorge Adilson; Rakitov, Roman A.; Rothschild, Mark J.; Sanborn, Allen F.; Takiya, Daniela M.; Wallace, Matthew S.; Zahniser, James N. 2022 onward."
