taxa_page_overview:
  panels:
    - - - panel:gallery
        - panel:descendants
        - panel:nomenclature

      - - panel:map
        - panel:type
        - panel:type-specimen
        - panel:nomenclature-references
        - panel:content
        - panel:statistics
